CREATE DATABASE Tienda;
USE Tienda;

DROP TABLE IF EXISTS Articulos;
CREATE TABLE Articulos(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
codigo VARCHAR(40) NOT NULL,
nombre VARCHAR(40) NOT NULL,
descripcion VARCHAR(40) NOT NULL,
existencia DOUBLE NOT NULL,
precio DOUBLE NOT null
);